/* 生成指定日期的运势数据文件 data/YYYY-MM-DD.js
 *
 * 用法：
 *   node scripts/generate.js            // 生成"今天"（Asia/Shanghai）
 *   node scripts/generate.js 2026-07-24 // 生成指定日期
 *
 * 内容来源（按优先级）：
 *   1) AI 生成 —— 配置 OPENAI_API_KEY 后，调用 OpenAI 兼容接口生成全新文案
 *      可选环境变量：OPENAI_BASE_URL（默认 https://api.openai.com/v1）
 *                    OPENAI_MODEL（默认 gpt-4o-mini）
 *   2) 文案池 —— 无 key 或 AI 生成失败时，用 generator.js 以日期为种子生成
 *
 * 规则：
 *   - 已存在的手工精修数据（无 AUTO-GENERATED 标记）不会被覆盖
 *   - 已存在的自动生成数据会被刷新
 */
const fs = require('fs');
const path = require('path');
require('../pool-extra.js'); // 先加载扩容文案池
const { generateDaily, SIGN_META } = require('../generator.js');

const dateStr = process.argv[2] ||
  new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Shanghai' }); // en-CA → YYYY-MM-DD

if (!/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
  console.error('日期格式应为 YYYY-MM-DD，收到:', dateStr);
  process.exit(1);
}

/* ===== AI 生成 ===== */
const DIMS = ['overall', 'career', 'wealth', 'love', 'health'];
const SIGN_KEYS = Object.keys(SIGN_META);

function buildPrompt(ds) {
  const signList = SIGN_KEYS.map(k =>
    `${k}（${SIGN_META[k].name} ${SIGN_META[k].symbol} ${SIGN_META[k].element}象 ${SIGN_META[k].dates}）`
  ).join('、');
  return `你是一位现代中文星座运势写手，风格：口语化、有心理洞察、给具体可执行的建议，不堆砌玄学词汇，不用"吉星高照"式陈词滥调。每条 detail 50-80 字，summary 10-16 字。

为 ${ds} 这一天创作十二星座运势。先虚构一段合理、具体的当日星象作为 overview（50-80 字，如行星换座、相位变化，每天有新意），并让各星座运势与该星象呼应。

严格输出 JSON（不要输出任何其他文字），结构如下：
{
  "date": "${ds}",
  "overview": "当日星象描述",
  "signs": {
    "${SIGN_KEYS[0]}": {
      "name": "星座中文名", "symbol": "符号", "element": "火|土|风|水", "dates": "日期范围",
      "overall": { "score": 1到5的整数, "summary": "...", "detail": "..." },
      "career": { 同结构 }, "wealth": { 同结构 }, "love": { 同结构 }, "health": { 同结构 },
      "luckyColor": "两字中文颜色词（各星座不同）",
      "luckyNumber": 1到12的整数
    },
    ... 其余11个星座同结构
  }
}

必须恰好包含这 12 个 key：${SIGN_KEYS.join(', ')}
星座列表：${signList}
评分应有区分度：大部分 3-4 分，每天 1-2 个星座 5 分，1-2 个星座 2 分，避免清一色高分。`;
}

function validate(data, ds) {
  if (!data || typeof data !== 'object') return '非对象';
  if (typeof data.overview !== 'string' || data.overview.length < 20) return 'overview 异常';
  if (!data.signs || typeof data.signs !== 'object') return 'signs 缺失';
  for (const k of SIGN_KEYS) {
    const s = data.signs[k];
    if (!s) return `缺少星座 ${k}`;
    for (const dim of DIMS) {
      const v = s[dim];
      if (!v || typeof v.summary !== 'string' || typeof v.detail !== 'string') return `${k}.${dim} 结构异常`;
      if (!Number.isInteger(v.score) || v.score < 1 || v.score > 5) return `${k}.${dim} score 异常`;
    }
    if (typeof s.luckyColor !== 'string' || !Number.isInteger(s.luckyNumber)) return `${k} 幸运项异常`;
  }
  data.date = ds;
  // 补全静态字段，防止 AI 写错
  for (const k of SIGN_KEYS) {
    Object.assign(data.signs[k], {
      name: SIGN_META[k].name, symbol: SIGN_META[k].symbol,
      element: SIGN_META[k].element, dates: SIGN_META[k].dates
    });
  }
  return null;
}

async function generateWithAI(ds) {
  const key = process.env.OPENAI_API_KEY;
  if (!key) return null;
  const base = (process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1').replace(/\/+$/, '');
  const model = process.env.OPENAI_MODEL || 'gpt-4o-mini';

  const res = await fetch(base + '/chat/completions', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + key },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: '你是星座运势内容生成器，只输出符合要求的 JSON。' },
        { role: 'user', content: buildPrompt(ds) }
      ],
      response_format: { type: 'json_object' },
      temperature: 0.9
    })
  });
  if (!res.ok) throw new Error('AI 接口 HTTP ' + res.status);
  const json = await res.json();
  const text = json.choices && json.choices[0] && json.choices[0].message && json.choices[0].message.content;
  if (!text) throw new Error('AI 返回为空');
  const data = JSON.parse(text);
  const err = validate(data, ds);
  if (err) throw new Error('AI 数据校验失败: ' + err);
  return data;
}

/* ===== 主流程 ===== */
(async () => {
  let data = null;
  let source = 'pool';
  if (process.env.OPENAI_API_KEY) {
    try {
      data = await generateWithAI(dateStr);
      source = 'ai';
    } catch (e) {
      console.warn('AI 生成失败，回退文案池:', e.message);
    }
  }
  if (!data) data = generateDaily(dateStr);

  const dir = path.join(__dirname, '..', 'data');
  const file = path.join(dir, dateStr + '.js');

  if (fs.existsSync(file)) {
    const head = fs.readFileSync(file, 'utf8').slice(0, 200);
    if (!head.includes('AUTO-GENERATED')) {
      console.log('跳过：' + file + ' 为手工精修数据，不覆盖');
      return;
    }
  }

  fs.mkdirSync(dir, { recursive: true });
  const body =
    '// AUTO-GENERATED by scripts/generate.js — ' + dateStr + '（来源: ' + source + '；如需精修请直接改写本文件并删除本行标记）\n' +
    'window.HOROSCOPE_OVERRIDE = ' + JSON.stringify(data, null, 2) + ';\n';
  fs.writeFileSync(file, body, 'utf8');
  console.log('已生成：' + file + '（来源: ' + source + '）');
})().catch(e => { console.error(e); process.exit(1); });
