/* 生成指定日期的运势数据文件 data/YYYY-MM-DD.js
 * 用法：
 *   node scripts/generate.js            // 生成"今天"（Asia/Shanghai）
 *   node scripts/generate.js 2026-07-24 // 生成指定日期
 * 规则：
 *   - 已存在的手工精修数据（无 AUTO-GENERATED 标记）不会被覆盖
 *   - 已存在的自动生成数据会被刷新为最新池子产出
 */
const fs = require('fs');
const path = require('path');
const { generateDaily } = require('../generator.js');

const dateStr = process.argv[2] ||
  new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Shanghai' }); // en-CA → YYYY-MM-DD

if (!/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
  console.error('日期格式应为 YYYY-MM-DD，收到:', dateStr);
  process.exit(1);
}

const data = generateDaily(dateStr);
const dir = path.join(__dirname, '..', 'data');
const file = path.join(dir, dateStr + '.js');

if (fs.existsSync(file)) {
  const head = fs.readFileSync(file, 'utf8').slice(0, 200);
  if (!head.includes('AUTO-GENERATED')) {
    console.log('跳过：' + file + ' 为手工精修数据，不覆盖');
    process.exit(0);
  }
}

fs.mkdirSync(dir, { recursive: true });
const body =
  '// AUTO-GENERATED by scripts/generate.js — ' + dateStr + '（如需精修请直接改写本文件并删除本行标记）\n' +
  'window.HOROSCOPE_OVERRIDE = ' + JSON.stringify(data, null, 2) + ';\n';
fs.writeFileSync(file, body, 'utf8');
console.log('已生成：' + file);
